### ISSUE TITLE
UI glitch when signing package

### ISSUE THREAD

**Issue by dsimog01** [dappnode/sdk-publish#33]
After clicking on sign release and performing the signing in metamask, the input box continues to have the "Release not signed". 

Then, after clicking the sign button again, "Release is already signed" is thrown.  We probably have to catch the event and mark the field valid, as it is confusing as it is now.

![image](https://github.com/dappnode/sdk-publish/assets/47595345/c01e842a-bdfa-4d1b-a1f0-f4ff3c1fffc1)

**Comment by pablomendezroyo** [comment]
Definitely a really need feature
